# Generated by Django 4.2.6 on 2024-01-11 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcementss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default='12:00:00')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.announcementss')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='announcementss',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='announcement_comments', through='announcement.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcementss',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='announcement_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AnnouncementPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_with_permissions', models.ManyToManyField(blank=True, related_name='announcement_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
