# Generated by Django 4.2.6 on 2024-01-11 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('sport_1', models.CharField(choices=[('Beginner', 'Beginner'), ('Medium', 'Medium'), ('Pro', 'Pro')], default='Basketball', max_length=100)),
                ('skill_level_1', models.CharField(choices=[('Beginner', 'Beginner'), ('Medium', 'Medium'), ('Pro', 'Pro')], default='Beginner', max_length=20)),
                ('sport_2', models.CharField(choices=[('Beginner', 'Beginner'), ('Medium', 'Medium'), ('Pro', 'Pro')], default='Football', max_length=100)),
                ('skill_level_2', models.CharField(choices=[('Beginner', 'Beginner'), ('Medium', 'Medium'), ('Pro', 'Pro')], default='Beginner', max_length=20)),
                ('sport_3', models.CharField(choices=[('Beginner', 'Beginner'), ('Medium', 'Medium'), ('Pro', 'Pro')], default='Table Tennis', max_length=100)),
                ('skill_level_3', models.CharField(choices=[('Beginner', 'Beginner'), ('Medium', 'Medium'), ('Pro', 'Pro')], default='Beginner', max_length=20)),
                ('location', models.CharField(default='none', max_length=100)),
                ('age', models.PositiveIntegerField(default=18)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('SECRET', 'SECRET')], default='MALE', max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
