# Generated by Django 4.2.6 on 2024-01-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sport_1',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Football', 'Football'), ('Table Tennis', 'Table Tennis'), ('Volleyball', 'Volleyball'), ('Swimming', 'Swimming'), ('Jogging', 'Jogging'), ('Badminton', 'Badminton')], default='Basketball', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sport_2',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Football', 'Football'), ('Table Tennis', 'Table Tennis'), ('Volleyball', 'Volleyball'), ('Swimming', 'Swimming'), ('Jogging', 'Jogging'), ('Badminton', 'Badminton')], default='Football', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sport_3',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Football', 'Football'), ('Table Tennis', 'Table Tennis'), ('Volleyball', 'Volleyball'), ('Swimming', 'Swimming'), ('Jogging', 'Jogging'), ('Badminton', 'Badminton')], default='Table Tennis', max_length=100),
        ),
    ]
