# Generated by Django 5.0.1 on 2024-01-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_sport_1_alter_profile_sport_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sport_1',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Swimming', 'Swimming'), ('Tennis', 'Tennis'), ('Badminton', 'Badminton'), ('Jogging', 'Jogging'), ('Table Tennis', 'Table Tennis'), ('Football', 'Football'), ('Volleyball', 'Volleyball'), ('Soccer', 'Soccer'), ('Baseball', 'Baseball'), ('Golf', 'Golf')], default='Basketball', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sport_2',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Swimming', 'Swimming'), ('Tennis', 'Tennis'), ('Badminton', 'Badminton'), ('Jogging', 'Jogging'), ('Table Tennis', 'Table Tennis'), ('Football', 'Football'), ('Volleyball', 'Volleyball'), ('Soccer', 'Soccer'), ('Baseball', 'Baseball'), ('Golf', 'Golf')], default='Football', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sport_3',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Swimming', 'Swimming'), ('Tennis', 'Tennis'), ('Badminton', 'Badminton'), ('Jogging', 'Jogging'), ('Table Tennis', 'Table Tennis'), ('Football', 'Football'), ('Volleyball', 'Volleyball'), ('Soccer', 'Soccer'), ('Baseball', 'Baseball'), ('Golf', 'Golf')], default='Table Tennis', max_length=100),
        ),
    ]
