# Generated by Django 4.2.6 on 2024-01-11 01:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue_list', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cancel', 'Cancel')], default='Basketball', max_length=100)),
                ('participant_number', models.PositiveIntegerField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_date', models.DateField(default=datetime.datetime(2024, 1, 11, 1, 7, 32, 540765, tzinfo=datetime.timezone.utc))),
                ('event_time', models.TimeField(default='12:00:00')),
                ('event_end_time', models.TimeField(default='14:00:00')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cancel', 'Cancel')], default='active', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue_list.venue')),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
