# Generated by Django 4.2.6 on 2024-01-11 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 11, 1, 8, 54, 759899, tzinfo=datetime.timezone.utc)),
        ),
    ]
