# Generated by Django 4.2.6 on 2024-01-11 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 11, 1, 13, 26, 326759, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='sport_type',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Football', 'Football'), ('Table Tennis', 'Table Tennis'), ('Volleyball', 'Volleyball'), ('Swimming', 'Swimming'), ('Jogging', 'Jogging'), ('Badminton', 'Badminton')], default='Basketball', max_length=100),
        ),
    ]
