# Generated by Django 4.2.6 on 2024-01-11 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_event_date_alter_post_sport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 11, 1, 19, 50, 489264, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='sport_type',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cancel', 'Cancel')], default='Basketball', max_length=100),
        ),
    ]
