# Generated by Django 5.0.1 on 2024-01-11 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_event_date_alter_post_sport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 11, 1, 20, 54, 813370, tzinfo=datetime.timezone.utc)),
        ),
    ]
