# Generated by Django 5.0.1 on 2024-01-11 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 11, 1, 23, 28, 358172, tzinfo=datetime.timezone.utc)),
        ),
    ]
