# Generated by Django 5.0.1 on 2024-01-11 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 11, 1, 38, 44, 625048, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='sport_type',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Swimming', 'Swimming'), ('Tennis', 'Tennis'), ('Badminton', 'Badminton'), ('Jogging', 'Jogging'), ('Table Tennis', 'Table Tennis'), ('Football', 'Football'), ('Volleyball', 'Volleyball'), ('Soccer', 'Soccer'), ('Baseball', 'Baseball'), ('Golf', 'Golf')], default='Basketball', max_length=100),
        ),
    ]
